/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const EpisodeInput = IDL.Record({
  'title' : IDL.Text,
  'durationSeconds' : IDL.Nat,
  'number' : IDL.Nat,
  'videoSource' : IDL.Text,
  'titleId' : IDL.Nat,
});
export const TitleType = IDL.Variant({
  'movie' : IDL.Null,
  'drama' : IDL.Null,
});
export const TitleInput = IDL.Record({
  'title' : IDL.Text,
  'kind' : TitleType,
  'published' : IDL.Bool,
  'description' : IDL.Text,
  'coverImage' : IDL.Text,
  'category' : IDL.Text,
  'releaseYear' : IDL.Nat,
});
export const ContentError = IDL.Variant({
  'notAuthorized' : IDL.Null,
  'invalidInput' : IDL.Text,
  'notFound' : IDL.Null,
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : ContentError });
export const TitleView = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'ratingCount' : IDL.Nat,
  'episodeCount' : IDL.Nat,
  'kind' : TitleType,
  'published' : IDL.Bool,
  'description' : IDL.Text,
  'averageRating' : IDL.Float64,
  'coverImage' : IDL.Text,
  'category' : IDL.Text,
  'releaseYear' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const HomeFeed = IDL.Record({
  'newlyAdded' : IDL.Vec(TitleView),
  'featured' : IDL.Vec(TitleView),
  'shortMovies' : IDL.Vec(TitleView),
  'shortDramas' : IDL.Vec(TitleView),
  'mostWatched' : IDL.Vec(TitleView),
});
export const RatingSummary = IDL.Record({
  'count' : IDL.Nat,
  'average' : IDL.Float64,
  'userRating' : IDL.Opt(IDL.Nat),
});
export const EpisodeView = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'durationSeconds' : IDL.Nat,
  'number' : IDL.Nat,
  'videoSource' : IDL.Text,
  'titleId' : IDL.Nat,
});
export const ContinueWatchingItem = IDL.Record({
  'title' : TitleView,
  'positionSeconds' : IDL.Nat,
  'updatedAt' : IDL.Int,
  'durationSeconds' : IDL.Nat,
  'episode' : EpisodeView,
});
export const TitleFilter = IDL.Record({
  'kind' : IDL.Opt(TitleType),
  'searchTerm' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result_1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addFavorite' : IDL.Func([IDL.Nat], [], []),
  'adminCreateEpisode' : IDL.Func([EpisodeInput], [IDL.Nat], []),
  'adminCreateTitle' : IDL.Func([TitleInput], [IDL.Nat], []),
  'adminDeleteEpisode' : IDL.Func([IDL.Nat], [Result], []),
  'adminDeleteTitle' : IDL.Func([IDL.Nat], [Result], []),
  'adminListTitles' : IDL.Func([], [IDL.Vec(TitleView)], ['query']),
  'adminSeedSampleContent' : IDL.Func([], [], []),
  'adminUpdateEpisode' : IDL.Func([IDL.Nat, EpisodeInput], [Result], []),
  'adminUpdateTitle' : IDL.Func([IDL.Nat, TitleInput], [Result], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHomeFeed' : IDL.Func([], [HomeFeed], ['query']),
  'getRatingSummary' : IDL.Func([IDL.Nat], [RatingSummary], ['query']),
  'getTitle' : IDL.Func([IDL.Nat], [IDL.Opt(TitleView)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listContinueWatching' : IDL.Func(
      [],
      [IDL.Vec(ContinueWatchingItem)],
      ['query'],
    ),
  'listEpisodes' : IDL.Func([IDL.Nat], [IDL.Vec(EpisodeView)], ['query']),
  'listFavorites' : IDL.Func([], [IDL.Vec(TitleView)], ['query']),
  'listTitles' : IDL.Func([TitleFilter], [IDL.Vec(TitleView)], ['query']),
  'rateTitle' : IDL.Func([IDL.Nat, IDL.Nat], [Result], []),
  'removeFavorite' : IDL.Func([IDL.Nat], [], []),
  'saveProgress' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const EpisodeInput = IDL.Record({
    'title' : IDL.Text,
    'durationSeconds' : IDL.Nat,
    'number' : IDL.Nat,
    'videoSource' : IDL.Text,
    'titleId' : IDL.Nat,
  });
  const TitleType = IDL.Variant({ 'movie' : IDL.Null, 'drama' : IDL.Null });
  const TitleInput = IDL.Record({
    'title' : IDL.Text,
    'kind' : TitleType,
    'published' : IDL.Bool,
    'description' : IDL.Text,
    'coverImage' : IDL.Text,
    'category' : IDL.Text,
    'releaseYear' : IDL.Nat,
  });
  const ContentError = IDL.Variant({
    'notAuthorized' : IDL.Null,
    'invalidInput' : IDL.Text,
    'notFound' : IDL.Null,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : ContentError });
  const TitleView = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'ratingCount' : IDL.Nat,
    'episodeCount' : IDL.Nat,
    'kind' : TitleType,
    'published' : IDL.Bool,
    'description' : IDL.Text,
    'averageRating' : IDL.Float64,
    'coverImage' : IDL.Text,
    'category' : IDL.Text,
    'releaseYear' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const HomeFeed = IDL.Record({
    'newlyAdded' : IDL.Vec(TitleView),
    'featured' : IDL.Vec(TitleView),
    'shortMovies' : IDL.Vec(TitleView),
    'shortDramas' : IDL.Vec(TitleView),
    'mostWatched' : IDL.Vec(TitleView),
  });
  const RatingSummary = IDL.Record({
    'count' : IDL.Nat,
    'average' : IDL.Float64,
    'userRating' : IDL.Opt(IDL.Nat),
  });
  const EpisodeView = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'durationSeconds' : IDL.Nat,
    'number' : IDL.Nat,
    'videoSource' : IDL.Text,
    'titleId' : IDL.Nat,
  });
  const ContinueWatchingItem = IDL.Record({
    'title' : TitleView,
    'positionSeconds' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'durationSeconds' : IDL.Nat,
    'episode' : EpisodeView,
  });
  const TitleFilter = IDL.Record({
    'kind' : IDL.Opt(TitleType),
    'searchTerm' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result_1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addFavorite' : IDL.Func([IDL.Nat], [], []),
    'adminCreateEpisode' : IDL.Func([EpisodeInput], [IDL.Nat], []),
    'adminCreateTitle' : IDL.Func([TitleInput], [IDL.Nat], []),
    'adminDeleteEpisode' : IDL.Func([IDL.Nat], [Result], []),
    'adminDeleteTitle' : IDL.Func([IDL.Nat], [Result], []),
    'adminListTitles' : IDL.Func([], [IDL.Vec(TitleView)], ['query']),
    'adminSeedSampleContent' : IDL.Func([], [], []),
    'adminUpdateEpisode' : IDL.Func([IDL.Nat, EpisodeInput], [Result], []),
    'adminUpdateTitle' : IDL.Func([IDL.Nat, TitleInput], [Result], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHomeFeed' : IDL.Func([], [HomeFeed], ['query']),
    'getRatingSummary' : IDL.Func([IDL.Nat], [RatingSummary], ['query']),
    'getTitle' : IDL.Func([IDL.Nat], [IDL.Opt(TitleView)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listContinueWatching' : IDL.Func(
        [],
        [IDL.Vec(ContinueWatchingItem)],
        ['query'],
      ),
    'listEpisodes' : IDL.Func([IDL.Nat], [IDL.Vec(EpisodeView)], ['query']),
    'listFavorites' : IDL.Func([], [IDL.Vec(TitleView)], ['query']),
    'listTitles' : IDL.Func([TitleFilter], [IDL.Vec(TitleView)], ['query']),
    'rateTitle' : IDL.Func([IDL.Nat, IDL.Nat], [Result], []),
    'removeFavorite' : IDL.Func([IDL.Nat], [], []),
    'saveProgress' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };