/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export type ContentError = { 'notAuthorized' : null } |
  { 'invalidInput' : string } |
  { 'notFound' : null };
export interface ContinueWatchingItem {
  'title' : TitleView,
  'positionSeconds' : bigint,
  'updatedAt' : bigint,
  'durationSeconds' : bigint,
  'episode' : EpisodeView,
}
export interface EpisodeInput {
  'title' : string,
  'durationSeconds' : bigint,
  'number' : bigint,
  'videoSource' : string,
  'titleId' : bigint,
}
export interface EpisodeView {
  'id' : bigint,
  'title' : string,
  'durationSeconds' : bigint,
  'number' : bigint,
  'videoSource' : string,
  'titleId' : bigint,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface HomeFeed {
  'newlyAdded' : Array<TitleView>,
  'featured' : Array<TitleView>,
  'shortMovies' : Array<TitleView>,
  'shortDramas' : Array<TitleView>,
  'mostWatched' : Array<TitleView>,
}
export interface RatingSummary {
  'count' : bigint,
  'average' : number,
  'userRating' : [] | [bigint],
}
export type Result = { 'ok' : null } |
  { 'err' : ContentError };
export type Result_1 = { 'ok' : null } |
  { 'err' : Error };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface TitleFilter {
  'kind' : [] | [TitleType],
  'searchTerm' : [] | [string],
  'category' : [] | [string],
}
export interface TitleInput {
  'title' : string,
  'kind' : TitleType,
  'published' : boolean,
  'description' : string,
  'coverImage' : string,
  'category' : string,
  'releaseYear' : bigint,
}
export type TitleType = { 'movie' : null } |
  { 'drama' : null };
export interface TitleView {
  'id' : bigint,
  'title' : string,
  'ratingCount' : bigint,
  'episodeCount' : bigint,
  'kind' : TitleType,
  'published' : boolean,
  'description' : string,
  'averageRating' : number,
  'coverImage' : string,
  'category' : string,
  'releaseYear' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addFavorite' : ActorMethod<[bigint], undefined>,
  'adminCreateEpisode' : ActorMethod<[EpisodeInput], bigint>,
  'adminCreateTitle' : ActorMethod<[TitleInput], bigint>,
  'adminDeleteEpisode' : ActorMethod<[bigint], Result>,
  'adminDeleteTitle' : ActorMethod<[bigint], Result>,
  'adminListTitles' : ActorMethod<[], Array<TitleView>>,
  'adminSeedSampleContent' : ActorMethod<[], undefined>,
  'adminUpdateEpisode' : ActorMethod<[bigint, EpisodeInput], Result>,
  'adminUpdateTitle' : ActorMethod<[bigint, TitleInput], Result>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'execute' : ActorMethod<[string], Result__1>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHomeFeed' : ActorMethod<[], HomeFeed>,
  'getRatingSummary' : ActorMethod<[bigint], RatingSummary>,
  'getTitle' : ActorMethod<[bigint], [] | [TitleView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listContinueWatching' : ActorMethod<[], Array<ContinueWatchingItem>>,
  'listEpisodes' : ActorMethod<[bigint], Array<EpisodeView>>,
  'listFavorites' : ActorMethod<[], Array<TitleView>>,
  'listTitles' : ActorMethod<[TitleFilter], Array<TitleView>>,
  'rateTitle' : ActorMethod<[bigint, bigint], Result>,
  'removeFavorite' : ActorMethod<[bigint], undefined>,
  'saveProgress' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'schema' : ActorMethod<[], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];