/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface Cell {
    value: Value;
    name: string;
}
export type ContentError = {
    __kind__: "notAuthorized";
    notAuthorized: null;
} | {
    __kind__: "invalidInput";
    invalidInput: string;
} | {
    __kind__: "notFound";
    notFound: null;
};
export interface ContinueWatchingItem {
    title: TitleView;
    positionSeconds: bigint;
    updatedAt: bigint;
    durationSeconds: bigint;
    episode: EpisodeView;
}
export interface EpisodeInput {
    title: string;
    durationSeconds: bigint;
    number: bigint;
    videoSource: string;
    titleId: bigint;
}
export interface EpisodeView {
    id: bigint;
    title: string;
    durationSeconds: bigint;
    number: bigint;
    videoSource: string;
    titleId: bigint;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface HomeFeed {
    newlyAdded: Array<TitleView>;
    featured: Array<TitleView>;
    shortMovies: Array<TitleView>;
    shortDramas: Array<TitleView>;
    mostWatched: Array<TitleView>;
}
export interface RatingSummary {
    count: bigint;
    average: number;
    userRating?: bigint;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: ContentError;
};
export type Result_1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface Result__1 {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export interface TitleFilter {
    kind?: TitleType;
    searchTerm?: string;
    category?: string;
}
export interface TitleInput {
    title: string;
    kind: TitleType;
    published: boolean;
    description: string;
    coverImage: string;
    category: string;
    releaseYear: bigint;
}
export interface TitleView {
    id: bigint;
    title: string;
    ratingCount: bigint;
    episodeCount: bigint;
    kind: TitleType;
    published: boolean;
    description: string;
    averageRating: number;
    coverImage: string;
    category: string;
    releaseYear: bigint;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum TitleType {
    movie = "movie",
    drama = "drama"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result_1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    addFavorite(titleId: bigint): Promise<void>;
    adminCreateEpisode(input: EpisodeInput): Promise<bigint>;
    adminCreateTitle(input: TitleInput): Promise<bigint>;
    adminDeleteEpisode(id: bigint): Promise<Result>;
    adminDeleteTitle(id: bigint): Promise<Result>;
    adminListTitles(): Promise<Array<TitleView>>;
    adminSeedSampleContent(): Promise<void>;
    adminUpdateEpisode(id: bigint, input: EpisodeInput): Promise<Result>;
    adminUpdateTitle(id: bigint, input: TitleInput): Promise<Result>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    execute(qJson: string): Promise<Result__1>;
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    getHomeFeed(): Promise<HomeFeed>;
    getRatingSummary(titleId: bigint): Promise<RatingSummary>;
    getTitle(id: bigint): Promise<TitleView | null>;
    isCallerAdmin(): Promise<boolean>;
    listContinueWatching(): Promise<Array<ContinueWatchingItem>>;
    listEpisodes(titleId: bigint): Promise<Array<EpisodeView>>;
    listFavorites(): Promise<Array<TitleView>>;
    listTitles(filter: TitleFilter): Promise<Array<TitleView>>;
    rateTitle(titleId: bigint, stars: bigint): Promise<Result>;
    removeFavorite(titleId: bigint): Promise<void>;
    saveProgress(episodeId: bigint, positionSeconds: bigint, durationSeconds: bigint): Promise<void>;
    schema(): Promise<string>;
}
import type { Cell as _Cell, ContentError as _ContentError, ContinueWatchingItem as _ContinueWatchingItem, EpisodeView as _EpisodeView, Error as _Error, HomeFeed as _HomeFeed, RatingSummary as _RatingSummary, Result as _Result, Result_1 as _Result_1, Result__1 as _Result__1, TitleFilter as _TitleFilter, TitleInput as _TitleInput, TitleType as _TitleType, TitleView as _TitleView, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addFavorite(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFavorite(arg0);
            return result;
        }
    }
    async adminCreateEpisode(arg0: EpisodeInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateEpisode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateEpisode(arg0);
            return result;
        }
    }
    async adminCreateTitle(arg0: TitleInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateTitle(to_candid_TitleInput_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateTitle(to_candid_TitleInput_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async adminDeleteEpisode(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteEpisode(arg0);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteEpisode(arg0);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminDeleteTitle(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteTitle(arg0);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteTitle(arg0);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListTitles(): Promise<Array<TitleView>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListTitles();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListTitles();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminSeedSampleContent(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSeedSampleContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSeedSampleContent();
            return result;
        }
    }
    async adminUpdateEpisode(arg0: bigint, arg1: EpisodeInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateEpisode(arg0, arg1);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateEpisode(arg0, arg1);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateTitle(arg0: bigint, arg1: TitleInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateTitle(arg0, to_candid_TitleInput_n5(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateTitle(arg0, to_candid_TitleInput_n5(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async execute(arg0: string): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result__1_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result__1_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHomeFeed(): Promise<HomeFeed> {
        if (this.processError) {
            try {
                const result = await this.actor.getHomeFeed();
                return from_candid_HomeFeed_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHomeFeed();
            return from_candid_HomeFeed_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRatingSummary(arg0: bigint): Promise<RatingSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getRatingSummary(arg0);
                return from_candid_RatingSummary_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRatingSummary(arg0);
            return from_candid_RatingSummary_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTitle(arg0: bigint): Promise<TitleView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTitle(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTitle(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listContinueWatching(): Promise<Array<ContinueWatchingItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listContinueWatching();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listContinueWatching();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async listEpisodes(arg0: bigint): Promise<Array<EpisodeView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEpisodes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEpisodes(arg0);
            return result;
        }
    }
    async listFavorites(): Promise<Array<TitleView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFavorites();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFavorites();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTitles(arg0: TitleFilter): Promise<Array<TitleView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTitles(to_candid_TitleFilter_n35(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTitles(to_candid_TitleFilter_n35(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async rateTitle(arg0: bigint, arg1: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.rateTitle(arg0, arg1);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rateTitle(arg0, arg1);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFavorite(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFavorite(arg0);
            return result;
        }
    }
    async saveProgress(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProgress(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProgress(arg0, arg1, arg2);
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
}
function from_candid_Cell_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ContentError_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentError): ContentError {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_ContinueWatchingItem_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContinueWatchingItem): ContinueWatchingItem {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_HomeFeed_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HomeFeed): HomeFeed {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_RatingSummary_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RatingSummary): RatingSummary {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_TitleType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TitleType): TitleType {
    return "movie" in value ? TitleType.movie : "drama" in value ? TitleType.drama : value;
}
function from_candid_TitleView_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TitleView): TitleView {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TitleView]): TitleView | null {
    return value.length === 0 ? null : from_candid_TitleView_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    ratingCount: bigint;
    episodeCount: bigint;
    kind: _TitleType;
    published: boolean;
    description: string;
    averageRating: number;
    coverImage: string;
    category: string;
    releaseYear: bigint;
}): {
    id: bigint;
    title: string;
    ratingCount: bigint;
    episodeCount: bigint;
    kind: TitleType;
    published: boolean;
    description: string;
    averageRating: number;
    coverImage: string;
    category: string;
    releaseYear: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        ratingCount: value.ratingCount,
        episodeCount: value.episodeCount,
        kind: from_candid_TitleType_n15(_uploadFile, _downloadFile, value.kind),
        published: value.published,
        description: value.description,
        averageRating: value.averageRating,
        coverImage: value.coverImage,
        category: value.category,
        releaseYear: value.releaseYear
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n19(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n23(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    newlyAdded: Array<_TitleView>;
    featured: Array<_TitleView>;
    shortMovies: Array<_TitleView>;
    shortDramas: Array<_TitleView>;
    mostWatched: Array<_TitleView>;
}): {
    newlyAdded: Array<TitleView>;
    featured: Array<TitleView>;
    shortMovies: Array<TitleView>;
    shortDramas: Array<TitleView>;
    mostWatched: Array<TitleView>;
} {
    return {
        newlyAdded: from_candid_vec_n12(_uploadFile, _downloadFile, value.newlyAdded),
        featured: from_candid_vec_n12(_uploadFile, _downloadFile, value.featured),
        shortMovies: from_candid_vec_n12(_uploadFile, _downloadFile, value.shortMovies),
        shortDramas: from_candid_vec_n12(_uploadFile, _downloadFile, value.shortDramas),
        mostWatched: from_candid_vec_n12(_uploadFile, _downloadFile, value.mostWatched)
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    count: bigint;
    average: number;
    userRating: [] | [bigint];
}): {
    count: bigint;
    average: number;
    userRating?: bigint;
} {
    return {
        count: value.count,
        average: value.average,
        userRating: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.userRating))
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: _TitleView;
    positionSeconds: bigint;
    updatedAt: bigint;
    durationSeconds: bigint;
    episode: _EpisodeView;
}): {
    title: TitleView;
    positionSeconds: bigint;
    updatedAt: bigint;
    durationSeconds: bigint;
    episode: EpisodeView;
} {
    return {
        title: from_candid_TitleView_n13(_uploadFile, _downloadFile, value.title),
        positionSeconds: value.positionSeconds,
        updatedAt: value.updatedAt,
        durationSeconds: value.durationSeconds,
        episode: value.episode
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notAuthorized: null;
} | {
    invalidInput: string;
} | {
    notFound: null;
}): {
    __kind__: "notAuthorized";
    notAuthorized: null;
} | {
    __kind__: "invalidInput";
    invalidInput: string;
} | {
    __kind__: "notFound";
    notFound: null;
} {
    return "notAuthorized" in value ? {
        __kind__: "notAuthorized",
        notAuthorized: value.notAuthorized
    } : "invalidInput" in value ? {
        __kind__: "invalidInput",
        invalidInput: value.invalidInput
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _ContentError;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: ContentError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_ContentError_n10(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TitleView>): Array<TitleView> {
    return value.map((x)=>from_candid_TitleView_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContinueWatchingItem>): Array<ContinueWatchingItem> {
    return value.map((x)=>from_candid_ContinueWatchingItem_n33(_uploadFile, _downloadFile, x));
}
function to_candid_TitleFilter_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TitleFilter): _TitleFilter {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_TitleInput_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TitleInput): _TitleInput {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_TitleType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TitleType): _TitleType {
    return value == TitleType.movie ? {
        movie: null
    } : value == TitleType.drama ? {
        drama: null
    } : value;
}
function to_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kind?: TitleType;
    searchTerm?: string;
    category?: string;
}): {
    kind: [] | [_TitleType];
    searchTerm: [] | [string];
    category: [] | [string];
} {
    return {
        kind: value.kind ? candid_some(to_candid_TitleType_n7(_uploadFile, _downloadFile, value.kind)) : candid_none(),
        searchTerm: value.searchTerm ? candid_some(value.searchTerm) : candid_none(),
        category: value.category ? candid_some(value.category) : candid_none()
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    kind: TitleType;
    published: boolean;
    description: string;
    coverImage: string;
    category: string;
    releaseYear: bigint;
}): {
    title: string;
    kind: _TitleType;
    published: boolean;
    description: string;
    coverImage: string;
    category: string;
    releaseYear: bigint;
} {
    return {
        title: value.title,
        kind: to_candid_TitleType_n7(_uploadFile, _downloadFile, value.kind),
        published: value.published,
        description: value.description,
        coverImage: value.coverImage,
        category: value.category,
        releaseYear: value.releaseYear
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
